# USE LOGISTIC REGRESSION MODEL

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [4]:
sns.heatmap(df.corr(),annot=True)

ValueError: could not convert string to float: 'male'

In [5]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [6]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df.drop(columns=["class","deck","alive","who","adult_male","embarked"],axis=1,inplace=True)

KeyError: "['class', 'deck', 'alive', 'who', 'adult_male', 'embarked'] not found in axis"

In [9]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare  embark_town  alone
0         0       3    male  22.0      1      0   7.2500  Southampton  False
1         1       1  female  38.0      1      0  71.2833    Cherbourg  False
2         1       3  female  26.0      0      0   7.9250  Southampton   True
3         1       1  female  35.0      1      0  53.1000  Southampton  False
4         0       3    male  35.0      0      0   8.0500  Southampton   True

In [10]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embark_town      2
alone            0
dtype: int64

In [11]:
df["age"].fillna(df["age"].mean(),inplace=True)
df["age"]=df["age"].astype(int)

C:\Users\rajpu\AppData\Local\Temp\ipykernel_16848\2965167255.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(),inplace=True)

In [12]:
df.dropna(subset=["embark_town"],inplace=True)

In [13]:
df.head()

   survived  pclass     sex  age  sibsp  parch     fare  embark_town  alone
0         0       3    male   22      1      0   7.2500  Southampton  False
1         1       1  female   38      1      0  71.2833    Cherbourg  False
2         1       3  female   26      0      0   7.9250  Southampton   True
3         1       1  female   35      1      0  53.1000  Southampton  False
4         0       3    male   35      0      0   8.0500  Southampton   True

In [14]:
df["embark_town"].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["sex"]=le.fit_transform(df["sex"])
df["embark_town"]=le.fit_transform(df["embark_town"])

In [16]:
df.head()

   survived  pclass  sex  age  sibsp  parch     fare  embark_town  alone
0         0       3    1   22      1      0   7.2500            2  False
1         1       1    0   38      1      0  71.2833            0  False
2         1       3    0   26      0      0   7.9250            2   True
3         1       1    0   35      1      0  53.1000            2  False
4         0       3    1   35      0      0   8.0500            2   True

In [17]:
df=df.astype(int)

In [35]:
from sklearn.preprocessing import StandardScaler
H_scaler=StandardScaler()
df[["age","fare"]]=H_scaler.fit_transform(df[["age","fare"]])

In [36]:
df

     pclass  sex       age  sibsp  parch      fare  embark_town  alone
0         3    1 -0.578023      1      0 -0.496733            2      0
1         1    0  0.655371      1      0  0.791539            0      0
2         3    0 -0.269675      0      0 -0.496733            2      1
3         1    0  0.424109      1      0  0.429213            2      0
4         3    1  0.424109      0      0 -0.476604            2      1
..      ...  ...       ...    ...    ...       ...          ...    ...
886       2    1 -0.192588      0      0 -0.375957            2      1
887       1    0 -0.809285      0      0 -0.033760            2      1
888       3    0 -0.038413      1      2 -0.174665            2      0
889       1    1 -0.269675      0      0 -0.033760            0      1
890       3    1  0.192848      0      0 -0.496733            1      1

[889 rows x 8 columns]

In [20]:
y=df["survived"]

In [21]:
df.drop(columns=["survived"],axis=1,inplace=True)

In [47]:
X=df
X.columns

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embark_town',
       'alone'],
      dtype='object')

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [40]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [41]:
y_predict=model.predict(X_test)

In [42]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [43]:
accuracy_score(y_test,y_predict)

0.8163265306122449

In [44]:
confusion_matrix(y_test,y_predict)

array([[157,  27],
       [ 27,  83]])

In [45]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85       184
           1       0.75      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

In [46]:
import joblib
joblib.dump(LogisticRegression,"Logistic_Regression.pkl")
joblib.dump(H_scaler,"H_scaler.pkl")
joblib.dump(X.columns.tolist(),"H_columns.pkl")

['H_columns.pkl']